<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LMS.ReviewService.Application\LMS.ReviewService.Application.csproj" />
    <ProjectReference Include="..\LMS.ReviewService.Domain\LMS.ReviewService.Domain.csproj" />
  </ItemGroup>

</Project>
